### ISSUE TITLE
Use Fog DNSimple API Auth

### ISSUE THREAD

**Issue by pwelch** [aetrion/chef-dnsimple#27] opened 2015-09-26 00:36 UTC
The Fog Gem now supports DNSimple API Auth [here](https://github.com/fog/fog/blob/master/lib/fog/dnsimple/dns.rb#L42).

For now the cookbook could use the latest fog gem until the cookbook can be changed to the dnsimple 2.0 Ruby gem mentioned on GH Issue #24

**Comment by patcon** [comment] 2015-09-30 22:22
Also seems to working for token domains, so long as `:dnsimple_domain` is passed in as well. I assume we could pass this in from the resource if *only* the token is supplied, and fog would carry on appropriately.

**Comment by patcon** [comment] 2015-09-30 22:24
Or wait, according the link in the OP, we can pass them all in, and so long as there's no password or email set, then it will work out.

**Comment by patcon** [comment] 2015-09-30 22:50
Would be nice to get some movement on this. I accidentally just re-implemented @pwelch's PR. (mine doesn't have breaking changes, fwiw)

**Comment by weppos** [comment] 2015-09-30 23:24
Friendly ping for @martinisoft @therobot

**Comment by martinisoft** [comment] 2016-01-08 09:00
To simplify things I am going to close this issue since its somewhat of a duplicate of #24 and we have two pull requests to try and get this shipped.

**Closed** 2016-01-08 09:00 UTC
